### ISSUE TITLE
C++ STL header errors on Rawhide

### ISSUE THREAD

**Issue by tokyovigilante** [tachoknight/swift-lang-packaging-fedora#2]
Hi,

I'm trying to build the `release/5.8` branch on an up-to-date Rawhide machine, but having a whole bunch of errors seemingly related to my C++ headers when building:
```
/usr/lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/initializer_list:88:5: error: redefinition of 'begin'
    begin(initializer_list<_Tp> __ils) noexcept
    ^
/usr/lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/initializer_list:88:5: note: previous definition is here
    begin(initializer_list<_Tp> __ils) noexcept
    ^
/home/ryan/Projects/Develop/swift-source/swift/include/swift/AST/ClangModuleLoader.h:19:10: note: while building module 'Clang_AST' imported from /home/ryan/Projects/Develop/swift-source/swift/include/swift/AST/ClangModuleLoader.h:19:
#include "clang/AST/DeclTemplate.h"
         ^
/home/ryan/Projects/Develop/swift-source/llvm-project/clang/include/clang/AST/APValue.h:16:10: note: while building module 'Clang_Basic' imported from /home/ryan/Projects/Develop/swift-source/llvm-project/clang/include/clang/AST/APValue.h:16:
#include "clang/Basic/LLVM.h"
         ^
/home/ryan/Projects/Develop/swift-source/llvm-project/clang/include/clang/Basic/Sanitizers.h:20:10: note: while building module 'LLVM_Transforms' imported from /home/ryan/Projects/Develop/swift-source/llvm-project/clang/include/clang/Basic/Sanitizers.h:20:
#include "llvm/Transforms/Instrumentation/AddressSanitizerOptions.h"
         ^
/home/ryan/Projects/Develop/swift-source/llvm-project/llvm/include/llvm/Transforms/Coroutines/CoroSplit.h:18:10: note: while building module 'LLVM_Analysis' imported from /home/ryan/Projects/Develop/swift-source/llvm-project/llvm/include/llvm/Transforms/Coroutines/CoroSplit.h:18:
#include "llvm/Analysis/CGSCCPassManager.h"
         ^
/home/ryan/Projects/Develop/swift-source/llvm-project/llvm/include/llvm/Analysis/IndirectCallPromotionAnalysis.h:16:10: note: while building module 'LLVM_ProfileData' imported from /home/ryan/Projects/Develop/swift-source/llvm-project/llvm/include/llvm/Analysis/IndirectCallPromotionAnalysis.h:16:
#include "llvm/ProfileData/InstrProf.h"
         ^
/home/ryan/Projects/Develop/swift-source/llvm-project/llvm/include/llvm/DebugInfo/Symbolize/SymbolizableModule.h:15:10: note: while building module 'LLVM_DebugInfo' imported from /home/ryan/Projects/Develop/swift-source/llvm-project/llvm/include/llvm/DebugInfo/Symbolize/SymbolizableModule.h:15:
#include "llvm/DebugInfo/DIContext.h"
         ^
/home/ryan/Projects/Develop/swift-source/llvm-project/llvm/include/llvm/DebugInfo/DIContext.h:18:10: note: while building module 'LLVM_Object' imported from /home/ryan/Projects/Develop/swift-source/llvm-project/llvm/include/llvm/DebugInfo/DIContext.h:18:
#include "llvm/Object/ObjectFile.h"
         ^
/home/ryan/Projects/Develop/swift-source/llvm-project/llvm/include/llvm/Object/Wasm.h:23:10: note: while building module 'LLVM_MC' imported from /home/ryan/Projects/Develop/swift-source/llvm-project/llvm/include/llvm/Object/Wasm.h:23:
#include "llvm/MC/MCSymbolWasm.h"
         ^
<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "MC/ConstantPools.h"
         ^
/home/ryan/Projects/Develop/swift-source/llvm-project/llvm/include/llvm/MC/ConstantPools.h:20:10: note: in file included from /home/ryan/Projects/Develop/swift-source/llvm-project/llvm/include/llvm/MC/ConstantPools.h:20:
#include <map>
         ^
/usr/lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/map:63:10: note: in file included from /usr/lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/map:63:
#include <bits/stl_map.h>
         ^
/usr/lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/stl_map.h:62:10: note: in file included from /usr/lib/gcc/x86_64-redhat-linux/13/../../../../include/c++/13/bits/stl_map.h:62:
#include <initializer_list>
         ^
```
These don't quite make sense, particularly regarding redefinition, so clearly something is being included twice somewhere.
` 
I have all the required dependencies installed using `dnf builddep` against the rpmspec.

**Comment by tachoknight** [comment]
Hi Ryan-

Yeah, I see this too with my F37 box. Did you install Rawhide from scratch or did you start with an earlier version, and if so, how many versions old was it? I _think_ it has something to do with something being incorrectly set after an upgrade somewhere; if you run the same process in a container it works fine and doesn't have these errors.

I'm looking into it as I'm worried it will become an issue that prevents Swift from being built at all.

If you do any digging or find anything, let me know!

**Comment by tachoknight** [comment]
BTW the command where it all goes sideways is:

`cd $HOME/rpmbuild/BUILD/swift-source/swift/SwiftCompilerSources && $HOME/rpmbuild/BUILD/swift-source/build/buildbot_linux/swift-linux-x86_64/bootstrapping0/bin/swiftc -c -o $HOME/rpmbuild/BUILD/swift-source/build/buildbot_linux/swift-linux-x86_64/bootstrapping1/SwiftCompilerSources/Basic.o -I $HOME/rpmbuild/BUILD/swift-source/build/buildbot_linux/swift-linux-x86_64/bootstrapping0/bin/../lib -I /usr/lib -target x86_64-unknown-linux-gnu -module-name Basic -emit-module -emit-module-path $HOME/rpmbuild/BUILD/swift-source/build/buildbot_linux/swift-linux-x86_64/bootstrapping1/SwiftCompilerSources/Basic.swiftmodule -parse-as-library $HOME/rpmbuild/BUILD/swift-source/swift/SwiftCompilerSources/Sources/Basic/SourceLoc.swift $HOME/rpmbuild/BUILD/swift-source/swift/SwiftCompilerSources/Sources/Basic/Utils.swift -wmo -Xfrontend -validate-tbd-against-ir=none -Xfrontend -enable-experimental-cxx-interop -Xcc -UIBOutlet -Xcc -UIBAction -Xcc -UIBInspectable -Xfrontend -disable-implicit-string-processing-module-import -O -cross-module-optimization -Xcc -I -Xcc $HOME/rpmbuild/BUILD/swift-source/llvm-project/llvm/include -Xcc -I -Xcc $HOME/rpmbuild/BUILD/swift-source/build/buildbot_linux/llvm-linux-x86_64/include -Xcc -I -Xcc $HOME/rpmbuild/BUILD/swift-source/llvm-project/clang/include -Xcc -I -Xcc $HOME/rpmbuild/BUILD/swift-source/build/buildbot_linux/llvm-linux-x86_64/tools/clang/include -Xcc -I -Xcc $HOME/rpmbuild/BUILD/swift-source/swift/include -Xcc -I -Xcc $HOME/rpmbuild/BUILD/swift-source/build/buildbot_linux/swift-linux-x86_64/SwiftCompilerSources/../include -I $HOME/rpmbuild/BUILD/swift-source/build/buildbot_linux/swift-linux-x86_64/bootstrapping1/SwiftCompilerSources`

**Comment by tokyovigilante** [comment]
Thanks Ron, this is on a system originally installed with FC32 then migrated to rawhide around FC35, so quite old. Good that it will build in a container but bad that there is this issue with existing systems. Will certainly let you know if I do resolve it. My last successful build was November 2022 for reference.

**Comment by tachoknight** [comment]
I’ll ask on the fedora dev forums and see if anyone has any suggestions on
what to check; the same comments I posted works fine, obviously, in the
container.

**Comment by tachoknight** [comment]
hey, didn't want you to think I've forgotten about this; had to get 5.8 out and just got 5.9 building properly (using Docker). I tried a few things but still haven't had any luck:

`dnf remove -y clang llvm gcc` then I used `dnf builddep -y ./swift-lang.spec` to reinstall, but still nothing. :( 

Now that 5.9 is at least building properly, I'll see if I can dig into this some more, outside of the usual work stuff.

**Comment by tokyovigilante** [comment]
Hey Ron, looks like this was ultimately due to/exposed by the CMake issue, I have just had a successful `-main` build with this PR - https://github.com/apple/swift/pull/65534

```
[Fri  8:47PM] ryan@crackotage ~/$ swift --version
Swift version 5.9-dev (LLVM b323659914f8062, Swift bb22acaf473c281)
Target: x86_64-unknown-linux-gnu
```

**Comment by tachoknight** [comment]
Ah ha, CMake strikes again; I had an issue with CMake as well that ended up being a patch in CMake, glad this was a much easier fix. Hopefully this will find its way into the 5.9 snapshots!

I'll close this issue when I can build it successfully myself. Thanks for taking the lead on getting this fixed!

**Comment by tachoknight** [comment]
I think I have an update that's even simpler: remove CMake. Based on your description above, I remembered I had an issue building Swift when a previous version of Swift was installed and it failed with a lot of weird errors. I removed the system CMake with `dnf remove -y cmake` and reran it and Swift built successfully.

**Comment by tachoknight** [comment]
I'm gonna close this one as I think we both found solutions :)
